### ISSUE TITLE
Why is my abundace estimation value zero for all classifications?

### ISSUE THREAD

**Issue by harisankar991** [infphilo/centrifuge#158]

**Comment by chilltrout** [comment]
Also very intrigued by this, went over the docs and I dont understand how to turn it on.
Im assuming abundance is always on because I have gotten numbers populated with a very high coverage genome on pacbio data but never on my nanopore data

**Comment by harisankarsadasivan** [comment]
Yes, makes sense. I faced the same with nanopore data, minion v9.4.1.

**Comment by shashibioinfo** [comment]
Hi sir,
even i had the same issue 
i have analyzed by minION nanopore data using centrifuge tool the output files shows abundance as zero.

how to resolve this ?
please help me any valuable suggestions will be appreciated

Thank you

**Comment by shashibioinfo** [comment]
> Yes, makes sense. I faced the same with nanopore data, minion v9.4.1.

even i have same issue 
if you have solved this can you please help me to resolve the issue
Thank you

**Comment by ExplodingCabbage** [comment]
I've seen the same thing. One species has >80% of all reads assigned to it, according to the output TSV, yet its abundance is still listed as 0.0, just like every other row.

**Comment by guokai8** [comment]
I have the same issue. I don't known why.

**Comment by mourisl** [comment]
Can you check whether there these are unique assignment or not? Thanks.

**Comment by guokai8** [comment]
Yes. I am sure there are unique reads here.

**Comment by Aiswarya-prasad** [comment]
Has anyone been able to resolve this? I am having the same issue with nanopore reads.

**Comment by mourisl** [comment]
I'm checking on this issue. The abundance estimation is on by default. Does any of the read's assignment to the subspecies(leaf) level? Can you show me a few lines of the report file? Thanks.

**Comment by jmaricb** [comment]
Hi, are there any updates with this issue? I seem to be getting zero abundances for every species. Here are the commands I have been using:

`centrifuge \
-x data/classifiers-DB/centrifuge/p_compressed+h+v \
-p 8 \
-f data/reads-fastq/ONT/communities-synthetic/integration_dataset.fasta \
-S out \
--report-file report`

`After that I also used this command to get kraken style report:
centrifuge-kreport \
-x data/classifiers-DB/centrifuge/p_compressed+h+v \
out > kraken_report`


You can download the output here: https://www.dropbox.com/s/a5j415ixyts9lox/Archive.zip?dl=0
You can see that there are species in the kraken_report file that have high abundance, and also in the report file you can see that there are species with high number of unique reads, but the abundance is still zero for all the rows.

**Comment by mourisl** [comment]
Thanks for sharing the files. I'll look into this.

**Comment by mourisl** [comment]
You are using the p_compressed+h+v index, however the seqId column is not in the form of cid|XXX from the compression. I guess the index you are using is actually p+h+v. Could you please check whether the index is correct?

**Comment by jmaricb** [comment]
Hi, thank you for the response. Sorry, I have sent you the data I have classified with custom database that I built from Bacteria and Archaea genomes.  The commands I used to build the database are:

`centrifuge-download -o taxonomy taxonomy`
`centrifuge-download -o library -m -d "archaea,bacteria" refseq > seqid2taxid.map`
`cat library/*/*.fna > input-sequences.fna `
`centrifuge-build -p 10 --conversion-table seqid2taxid.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp input-sequences.fna abv `

I think that succeeded, because as you can see the kraken report gives reasonable classification.

I am now sending new data: https://www.dropbox.com/s/cefkjfz0a4kq1ig/Data.zip?dl=0
- There is the folder 'custom' which contains the output, report and kraken-report for the dataset classified with that custom index.
- There is the folder 'default' which contains the output, report and kraken-report for the same dataset clasdified with the p_compressed+h+v index
- And finally there is the folder integration that contains small dataset which when classified to p_compressed+h+v index gives abundances that are not zero. I don't know why. The output and the report are inside the directory.

Here is the dataset I've been using. It's quite large so I am sending it separately:
https://www.dropbox.com/s/jeuaho0slc45p9w/silico.fastq.zip?dl=0

**Comment by jmaricb** [comment]
@mourisl Hi, one more thing. I don't know if it can help. But my integration.fastq dataset also works with custom index that I created, so the problem might not be in the indexes. 

Here are the results of the classification with the custom index: https://www.dropbox.com/s/iojc2br7q17ru1m/integration_custom.zip?dl=0

**Comment by jmaricb** [comment]
@mourisl 
Hi,
can you just help me to calculate the abundances by myself. I would like to do that, but in the centrifuge output reads are classified to multiple species. How can I determine to which species each read should classify? Is there a way for centrifuge to determine one species to which certain read should classify to?

Thank You.

**Comment by mourisl** [comment]
@jmaricb You can directly use the abundance from kreport. For the multiple-assigned reads, the count will be added to their lowest ancestor in the taxonomy tree. You can also use "--no-lca" in kreport, which add the count to a strain in the fraction of the number of assignment.

**Comment by jmaricb** [comment]
@mourisl 
Sorry for bothering you, but just one more question.
If I have a read that is mapped to three tax ids, like this:
SRR5891470.22869	species	106654	676	676	41	2302	3
SRR5891470.22869	species	470	676	676	41	2302	3
SRR5891470.22869	NZ_CP033858.1	2420300	676	676	41	2302	3

In the report (let's say kreport), this read will be assigned to lowest ancestor of these three tax ids (106654, 470, 2420300), which is Acinetobacter (tax id = 469)? Am I right? 

Does this mean that only reads that map to single species will be assigned to that species?

Thank You.

**Comment by mourisl** [comment]
@jmaricb Yes, that is the default behavior of kreport. You can use "--no-lca" in centrifuge-kreport to put fraction of a read to the species. Note that, Centrifuge already assigns a read to its lowest common ancestor if it assigned to too many species (-k option).

**Comment by jmaricb** [comment]
@mourisl 
Thank you very much. I think I got everything I need to calculate the abundances. 

May I just know one last thing. 
"--no-lca Do not report the LCA of multiple assignments, but report count fractions at the taxa."

How do you calculate count fractions for each species from multiple assignments when you use --no-lca?

**Comment by mourisl** [comment]
@jmaricb If a read is assigned to 4 species, the the four species' abundance will add 0.25.

**Comment by jmaricb** [comment]
Thank You for you help.

**Comment by Adoni5** [comment]
@mourisl 

I am also using a compressed index (p_compressed hosted on the site) with nanopore reads, and am getting an abundance of 0. I am building a custom index of bacteria from refseq to test if the compressed indexes are the problem, but was wondering of there is anything else you would recommend trying?

Sample ouput  - 
```
readID	seqID	taxID	score	2ndBestScore	hitLength	queryLength	numMatches
2bef9c72-eeab-4b54-b7a0-4f4696866878	NC_018695.1	1229205	225	225	30	215	2
a6d6c54d-b1e2-45ee-858f-0cb61d0fc2f5	NZ_CP016077.1	1612551	121	121	26	439	2
```

Sample report - 
```
name	taxID	taxRank	genomeSize	numReads	numUniqueReads	abundance
Myxococcales	29	order	9697933	1	0	0.0
Cystobacter fuscus	43	species	12349744	1	1	0.0
```

**Comment by Aiswarya-prasad** [comment]
I hope that I am not repeating something that someone else has already brought up. I think this might help resolve this issue though.
The header of the output is :
`readID	seqID	taxID	score	2ndBestScore	hitLength	queryLength	numMatches`
However, the second last column is the taxID. I know this because, below are the lines corresponding to a set of reads that were classified as Faecalibacterium prausnitzii (taxID 853) by another tool (Kraken2):
```
247005c4-c0f5-452b-9722-17c32dcb37e8	cid|1834198	1834198	144	0	27	853	1

09e262a0-4c23-4a59-9721-0db4dd72da71	NC_011222.1	99179	2714	0	187	853	1

2c62c537-9e64-4a0a-93b1-59408fbab480	cid|1336	1336	144	144	27	853	2

2c62c537-9e64-4a0a-93b1-59408fbab480	cid|1328	1328	144	144	27	853	2

732353ab-2cd4-463f-882d-8c6baefdf0fb	NC_000017.11	9606	8654	0	432	853	1
```
The queryLength and taxID columns seem to have been mixed up. Also, this taxon (853) did not appear in the report at all! Is it possible that the report ends up being faulty because of the columns being mixed up?

**Comment by xiechangxiao** [comment]
I have the same issue. The abundance value always get 0 when I use the latest verion centrifuge and h+p+v+c database analysis nanopore data. Could you help me correct it, thank you.
Here is my code.
`centrifuge -x database/centrifuge_databases/hpvc/hpvc -U BC_25.fq.gz --report-file BC_25.report -S BC_25.output`

**Comment by tanushrin** [comment]
I am having issue with the abundance estimation; getting 0 abundances for most of the species except one species (with abundance value: 1).  In the centrifuge_report.txt, there are species with high abundance however, centrifuge_report.tsv shows abundance as 0.
I created a custom database : archaea, bacteria, protozoa, fungi, plant, algae

Here are the centrifuge commands I have been using:

centrifuge-build -p 24  --conversion-table $REF_SEQ_DIR/accession2taxid_cent.map --taxonomy-tree $REF_SEQ_DIR/nodes.dmp --name-table $REF_SEQ_DIR/names.dmp  $DB.fa $DB > $DB.log

centrifuge -p 24  -x $DB  -q in.fq > out.txt

centrifuge-kreport -x $DB out.txt > centrifuge_report.txt

How to get proper(non-zero) abundance values?  Would appreciate any help.

Thank you!

**Comment by Kumereng** [comment]
Hi i have exactly that same issue which has not been resolved. The abundance is also zero.

**Comment by lixiaopi1985** [comment]
same issue with the latest Centrifuge.

**Comment by mourisl** [comment]
I just fixed an issue with estimating average genome sizes, which was also related to the abundance estimation procedure. Could you please try the new version and check whether the abundance values become normal? You don't need to rebuild the index.

**Comment by BaylorLyu** [comment]
The problem still have incurrent version，only few cloumn have abundace value

**Comment by BaylorLyu** [comment]
> I just fixed an issue with estimating average genome sizes, which was also related to the abundance estimation procedure. Could you please try the new version and check whether the abundance values become normal? You don't need to rebuild the index.

The problem still have in current version，only few cloumn have abundace value

**Comment by mourisl** [comment]
I can reproduce the zero abundance issue on one of the data sets. I'm working on it now, and it seems more complex than I thought.

**Comment by sybrohee** [comment]
@mourisl Thank you for considering the issue (and all your nice work with centrifuge)

**Comment by mourisl** [comment]
I finally noticed that Centrifuge only utilizes perfectly classified (all matches) reads for abundance estimation. I know this has been a while, so for future users, if you find the abundance estimation is all 0s, could you please check whether that non of the reads are perfectly classified (hitLength == queryLength).

I also implement an abundance estimation method in Centrifuge's spiritual successor, Centrifuger, and put a script to requantify the abundances using Centrifuge's output (https://github.com/mourisl/centrifuger/blob/master/scripts/requant-centrifuge.pl). Centrifuger's quantification does not hard filter imperfect classifications, but assigns them a lower weight. Hope this will help.
