### ISSUE TITLE
Indices makefile failed - grep: .listing: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [infphilo/centrifuge#29]
```
make b_compressed+h+v THREADS=72

Making: b_compressed+h+v: b_compressed+h+v
make -f Makefile IDX_NAME=b_compressed+h+v
make[1]: Entering directory `/mnt/seq/KRAKEN/centrifuge'
mkdir -p reference-sequences
[[ -d tmp_b_compressed+h+v ]] && rm -rf tmp_b_compressed+h+v; mkdir -p tmp_b_compressed+h+v
Downloading and dust-masking viral
centrifuge-download -o tmp_b_compressed+h+v  -m -d "viral" -P 72 refseq > \
        tmp_b_compressed+h+v/all-viral.map
grep: .listing: No such file or directory
viral is not a valid domain - use one of the following:
grep: .listing: No such file or directory
make[1]: *** [reference-sequences/all-viral.fna] Error 2
make[1]: Leaving directory `/mnt/seq/KRAKEN/centrifuge'
make: *** [b_compressed+h+v] Error 2
```

Here's the file status:

```
% find .
.
./Makefile
./reference-sequences
./tmp_b_compressed+h+v
./tmp_b_compressed+h+v/all-viral.map
```

and that last `.map` file is empty.

**Comment by fbreitwieser** [comment]
Hi @tseemann , there was a change in the FTP authorization which caused the curl command to not get the listing. Should work now with the most current GitHub code.

**Comment by sjaenick** [comment]
Same here (and still occurs for current master branch); I tracked this down to centrifuge-download using wget (GNU Wget 1.15), which does not produce a .listing file if a proxy server is being used:

```
[sjaenick@lummerland:~ ]$ wget -qO- --no-remove-listing ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/ > /dev/null ; file .listing ; rm -f .listing
.listing: ASCII text, with CRLF line terminators
[sjaenick@lummerland:~ ]$ ftp_proxy=http://redacted.host.xy:3128 wget -qO- --no-remove-listing ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/ > /dev/null ; file .listing ; rm -f .listing
.listing: ERROR: cannot open `.listing' (No such file or directory)
```

**Comment by fbreitwieser** [comment]
Should work now. Can you try it again?

**Comment by sjaenick** [comment]
works for me.

**Comment by fbreitwieser** [comment]
@tseemann , feel free to reopen if it still doesn't work for you.
